### ISSUE TITLE
lol did you forget this repo

### ISSUE THREAD

**Issue by osbm** [0atman/nixos#1]
If it is not sensitive can we see your nixos config?

I watched your video and i have been using nixos for a while now. All thanks to you.

**Comment by 0atman** [comment]
I did indeed forget this repo! Glad you're having a good time with nixos, me too! :grin: 

My only point of customisation is my rebuild script, which has had a great conversation around it https://gist.github.com/0atman/1a5133b842f929ba4c1e195ee67599d5

I'll remove this nixos repo in a day, just to tidy things up.
